defmodule AshPostgresPartition.Test.Repo.TenantMigrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:resource_range, primary_key: false, prefix: prefix(), options: "PARTITION BY RANGE(key)") do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :key, :utc_datetime_usec, null: false, primary_key: true
      add :data, :text
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:resource_list, primary_key: false, prefix: prefix(), options: "PARTITION BY LIST(key)") do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :key, :text, null: false, primary_key: true
      add :data, :text
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:resource_hash, primary_key: false, prefix: prefix(), options: "PARTITION BY HASH(key)") do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :key, :bigint, null: false, primary_key: true
      add :data, :text
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:resource_hash, prefix: prefix())

    drop table(:resource_list, prefix: prefix())

    drop table(:resource_range, prefix: prefix())
  end
end
